# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
