# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_brew_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
